### ISSUE TITLE
initSignature() always return true value

### ISSUE THREAD

**Issue by praba1989** [googlesamples/android-AsymmetricFingerprintDialog#10]
Hi,

  initSignature() getting always true value. Can anyone help me when it's getting false.

**Comment by blabno** [comment]
Theoretically when you enroll new fingerprint the key should be invalidated, but apparently it is not.

**Comment by blabno** [comment]
Apparently key invalidation does not work on emulators so you have to test it on a real device with system >=8.1.
https://issuetracker.google.com/issues/65578763

**Comment by codingjeremy** [comment]
This sample has been updated to Kotlin and migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
