### ISSUE TITLE
FingerprintManager.authenticate and FingerprintManager.hasEnrolledFingerprints was deprecated in API level 28

### ISSUE THREAD

**Issue by dawud-tan** [googlesamples/android-AsymmetricFingerprintDialog#11]
Hello, FingerprintManager.authenticate and FingerprintManager.hasEnrolledFingerprints was deprecated in API level 28.

**Comment by codingjeremy** [comment]
This sample has been updated to Kotlin and migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
