### ISSUE TITLE
Please fix dagger compiler dependencie for gradle plugin 3.x and move to androidx

### ISSUE THREAD

**Issue by smokienko** [googlesamples/android-AsymmetricFingerprintDialog#12]
Currently dagger compiler p[roviced as a `compile 'com.squareup.dagger:dagger-compiler:1.2.2'` but should be `annotationProcessor 'com.squareup.dagger:dagger-compiler:1.2.2'` for newer versionfs of gradle plugin.

Also, it would be great if you can migrate it to androidx as well.

**Comment by codingjeremy** [comment]
This sample has been updated to Kotlin and migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
