### ISSUE TITLE
Encrypting and Decrypting using the Asymmetric Key

### ISSUE THREAD

**Issue by santbob** [googlesamples/android-AsymmetricFingerprintDialog#6]
Can you please provide an example of how to encrypt and decrypt a string using the algorithm `EC` used in this sample.

Also if you can provide the alternate way of using RSA alogrithm for doing the FingerPrint Auth, it would be great.

**Comment by bilaizi** [comment]
can you please change dependency injection framework to dagger2, I  have difficulty in Migrating from Dagger 1 to Dagger 2

**Comment by codingjeremy** [comment]
This sample has been updated to Kotlin and migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
