### ISSUE TITLE
This project is working fine,but facing one issue is that when user register fingerprint then a key is generated at that time for different users.And When user login through fingerprint then different key is generated.The issue is that same user have different keys at register and login fingerprints,how to solve that issue.

### ISSUE THREAD

**Issue by kapoorsurbhi** [googlesamples/android-AsymmetricFingerprintDialog#7]

**Comment by codingjeremy** [comment]
This sample has been updated to Kotlin and migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
