### ISSUE TITLE
how to generate asymmetric key for register and login fingerprint.

### ISSUE THREAD

**Issue by kapoorsurbhi** [googlesamples/android-AsymmetricFingerprintDialog#8]

**Comment by codingjeremy** [comment]
This sample has been updated to Kotlin and migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
